# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: iOS Safari Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install ffmpeg codec
        run: brew install ffmpeg
      - name: Install Appium Server
        run: npm install -g appium
      - name: Run Appium Server
        run: appium -p 4723 --log appium.log &
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew clean test -Denv=iphone.12.pro.max.safari -DincludeGroups=ui.test.example --info
      - name: Print Appium logs
        if: ${{ always() }}
        run: cat appium.log
      - name: Download Allure CLI
        if: ${{ always() }}
        run: ./gradlew downloadAllure
      - name: Generate report
        run: ./gradlew allureReport
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./build/reports/allure-report
