# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew clean test -Denv=cats.api -DincludeGroups=api.test.example --info
      - name: Download Allure CLI
        if: ${{ always() }}
        run: ./gradlew downloadAllure
      - name: Generate report
        run: ./gradlew allureReport
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./build/reports/allure-report
